version: '2'
services:
  jhipsterangularsample-app:
    image: jhipsterangularsample
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterangularsample-postgresql:5432/jhipsterangularsample
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipsterangularsample-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipsterangularsample-elasticsearch:9200
    ports:
      - 8080:8080
  jhipsterangularsample-postgresql:
    extends:
      file: postgresql.yml
      service: jhipsterangularsample-postgresql
  jhipsterangularsample-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipsterangularsample-elasticsearch
